### PR TITLE
Safety async completions (unhook events, cancel task completion sources, etc) & Add CancellationTokens

### PR DESCRIPTION
**Pull request by aritchie**
Please take a moment to fill out the following:
There are ways where iOS can get itself into trouble and get into a "stuck" state without any workaround.  By adding cancellation tokens, users can get themselves out of trouble (ie. app is backgrounding, cancel task) which will release any events that are pinned as well as cancel out the task completion sources.

Fixes # .

Changes Proposed in this pull request:
- Drop params args to add CancellationTokens
- Safety most of the Apple calls to prevent things from getting into a "stuck" state
- Safety-ish some of the Android calls.  The underlying bindings need some work to respect cancellation

I have not updated the samples or any docs.  This is a proposal and does have breaking changes.  I also only test in production 👍

### CODE REVIEW

**Comment by aritchie** [comment]
@Redth FYI - this is a more complete fix for you.  Yes... you need to add cancellation tokens like a good dev though I've included defaults on the CTs for those who want to play roulette

**Comment by aritchie** [comment]
Kill off #601

**Comment by jamesmontemagno** [comment]
Looks like will need a little code changes in this to build

**Comment by aritchie** [comment]
Ya I'll fix everything up with the samples.  I wanted to make sure you were fine with the breaking changes that are incoming first.

**Comment by jamesmontemagno** [comment]
go for it and i will bump numbers, also please update docs if possible ;)

**Comment by jamesmontemagno** [comment]
Also, i am fine at this point dropping xamarin tfms and also bumping to require .net 8

**Comment by aritchie** [comment]
.NET 8 is done-ish.  There isn't enough setup for testing.  I elect @Redth :)

Also, I did docs... so someone owes me a beer

**Comment by jamesmontemagno** [comment]
who needs tests?!??!1 we do it live!

**Comment by jamesmontemagno** [comment]
going to setup the ci now for .net 8

**Comment by jamesmontemagno** [comment]
And we are green! @Redth you can download the nugets to give it a try from DevOps

**Pull request merged**
