### PR TITLE
Trying to get purchase Token on GetPurchase

### LINKED ISSUE #270: Restored Purchase is Missing PurchaseToken
When restoring purchases on iOS, the purchases that are returned do not have the purchase token.  Is this by design?

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: iPhone 7 Plus / iOS 12.4
Simulator Tested On: N/A
Version of VS: VS 2019 for Mac 8.3.10(build 2)
Version of Xamarin: 4.2.0.778463
Versions of other things you are using:

### Steps to reproduce the Behavior

Note that this is when using test purchases. I cannot say what the behavior would be during a real purchase, but I assume it would be the same.

Attempt the get purchases async call

`var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);`

### Expected Behavior

InAppBillingPurchase's PurchaseToken should have a value from the original receipt

### Actual Behavior

PurchaseToken is always null/empty string

### PR DESCRIPTION
**Pull request by stevewinn74**
Please take a moment to fill out the following:

Fixes #270

Changes Proposed in this pull request:
Trying to get purchase Token on GetPurchase

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Simplified logic a bit. Take a look. This will go into 4.0.0

**Comment by stevewinn74** [comment]
Looks good.

**Comment by stevewinn74** [comment]
Fixes #278

**Comment by stevewinn74** [comment]
Fixes #287

**Comment by stevewinn74** [comment]
@jamesmontemagno any chance you can approve release 38 onto nuget?
 https://dev.azure.com/jamesmontemagno/Plugins%20for%20Xamarin/_release?definitionId=15&view=mine&_a=releases

**Pull request merged**
