### PR TITLE
Start implementation of new billing

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Please take a moment to fill out the following:

Fixes # .

Changes Proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by Dexus** [comment]
Hi @jamesmontemagno you should be sure to use the latest Goole Billing API (v3.0) if not your app will rejected and not published anymore also your app will removed from the playstore. So my question now is Xamarin.Android.Google.BillingClient 3.0 equivalent to API 3.0?

Best regards, Josef

**Comment by jamesmontemagno** [comment]
yeah, we already updated to 3.0.

Also, that is different that is for the server, not in the app. it is confusing.

**Comment by Dexus** [comment]
> yeah, we already updated to 3.0.
> 
> Also, that is different that is for the server, not in the app. it is confusing.

Thanks for the info.

**Comment by dmariogatto** [comment]
I noticed that the signature of `GetPurchasesAsync` has changed to no longer accept an instance of `IInAppBillingVerifyPurchase`. Is there a reason restoring previous purchases no longer requires validation?

**Comment by jamesmontemagno** [comment]
It exists,

```
Task<IEnumerable<InAppBillingPurchase>> GetPurchasesAsync(ItemType itemType);
```

**Pull request merged**
