### PR TITLE
Fixed bug w/ null vs. empty payload string

### LINKED ISSUE #41: PurchaseAsync returns null InAppBillingPurchase result after a successful purchase
## Bug 

Version Number of Plugin: 1.1.0.35-beta
Device Tested On: Samsung Galaxy S5 (Android 6.0.1)

### Expected Behavior

On a successful purchase, PurchaseAsync completes with a non-null InAppBillingPurchase.

### Actual Behavior

All indications are that the purchase succeeded (Google Play reports success) but the task result is null. Looking at the account subscriptions in the Google Play app, I can see that the subscription purchase did complete.

I also verified that my OnActivityResult is being called with requestCode=1001, resultCode=Ok, and responseCode=0, and this is being passed along to InAppBillingImplementation.HandleActivityResult.

I'm seeing this for a subscription purchase *and* when purchasing a consumable product.
Note: shortly after the purchase was started, the log shows the following suspicious error:

```
04-29 22:58:36.537: I/MainActivity(21441): PurchaseSubscription: connected, purchasing
04-29 22:58:36.542: I/Finsky(9080): [535] com.google.android.finsky.billing.iab.y.a(32): com.performancephones.crewnerd: Account determined from library ownership - [Ohz2sWuzKyd7LW40g-gyu0tWluk]
04-29 22:58:36.552: E/Parcel(4385): Class not found when unmarshalling: com.google.android.finsky.billing.common.PurchaseParams
04-29 22:58:36.552: E/Parcel(4385): java.lang.ClassNotFoundException: com.google.android.finsky.billing.common.PurchaseParams
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.Class.classForName(Native Method)
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.Class.forName(Class.java:324)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Parcel.readParcelable(Parcel.java:2358)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Parcel.readValue(Parcel.java:2264)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.BaseBundle.getString(BaseBundle.java:920)
04-29 22:58:36.552: E/Parcel(4385): 	at android.content.Intent.getStringExtra(Intent.java:6183)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:6874)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:310)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6632)
04-29 22:58:36.552: E/Parcel(4385): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:292)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3995)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Binder.execTransact(Binder.java:453)
04-29 22:58:36.552: E/Parcel(4385): Caused by: java.lang.ClassNotFoundException: com.google.android.finsky.billing.common.PurchaseParams
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.Class.classForName(Native Method)
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-29 22:58:36.552: E/Parcel(4385): 	... 17 more
04-29 22:58:36.552: E/Parcel(4385): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

### Steps to reproduce the Behavior

Call ConnectAsync followed by PurchaseAsync for a subscription or consumable product.

Looking at the code here, I see that there are several reasons why PurchaseAsync can return null. To eliminate one of those possibilities, I removed the "verify" parameter from my purchase calls. The behavior was the same.

It looks like there may be a race condition between PurchaseAsync and the HandleActivityResult callback. tcsPurchase is being set *after* the call to serviceConnection.Service.GetBuyIntent which I think allows the HandleActivityResult call happen while tcsPurchase is still null.

### PR DESCRIPTION
**Pull request by CrewNerd**
Added code to prevent a problem with empty payload strings being
deserialized as null. Also moved a TCS initialization to prevent a
potential race condition.

Fixes #41

Changes Proposed in this pull request:
- Promote null payloads to string.Empty to prevent confusion between the two. Empty payload strings get deserialized as null causing it to appear as though the purchase failed.
- Initialize tcsPurchase earlier to prevent a possible race condition.

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Did this occur because you didn't pass in a payload?

**Comment by CrewNerd** [comment]
I wasn't clear on the purpose of the payload, so I passed in an empty string. That it was deserialized as a null seems like an Android bug. Looking at the Android docs on this now, it looks like using it is only a *recommended* best practice, so it seems a little extreme to require it to be non-empty.

**Comment by jamesmontemagno** [comment]
So there are several other places where payloads are passed in.

I would prefer to not actually at all allow use of a non-payload even if recommended, silly not to seeing it opens up your app to security holes.

However, I think the actual fix is that... 
* payloads != null
* when payload is de-serialized if it is null then change to string.empty

**Comment by jamesmontemagno** [comment]
Implemented in #46

**Pull request closed without merging**
