### PR TITLE
Android subscriptions upgrade, downgrade and change

### LINKED ISSUE #26: [Feature Request] Ability to Upgrade/Downgrade Subscriptions
## Feature Request:
I took a quick look at your code and didn't find anything with name "getBuyIntentExtraParams" like it is described in https://developer.android.com/google/play/billing/billing_reference.html#getBuyIntentExtraParams.

Is this correct?

I am asking as I want to provide upgrade and downgrade functionality for subscriptions.

Is it correct, that the only current possibility to up and downgrade Android subscriptions is to let the user manually cancel an old subscription and than let him buy a new one? The problem here would be that already paid money can't be prorated with the new subscription.

### PR DESCRIPTION
**Pull request by RadoslawKubas**
Fixes #26 

Changes Proposed in this pull request:

New UpgradePurchasedSubscriptionAsync function is implemented for Android. It uses similar interface as #192 but implementation works fine with latest api. Implementation for iOS is not necessary, because iOS support upgrades/downgrades itself. I didn't check UWP.

### CODE REVIEW

**Comment by RadoslawKubas** [comment]
@jamesmontemagno Hello, is there a chance to merge this pull request (or any other Android subscription update implementation)? If so, when?

**Comment by RadoslawKubas** [comment]
@jamesmontemagno Hello, any update here? :)

**Comment by codexguy** [comment]
> @jamesmontemagno Hello, any update here? :)
I too am interested in getting this functionality. Thank you.

**Comment by jamesmontemagno** [comment]
If this can be rebased on the latest and updated to the latest android billing which is now used I will pull it in.

**Comment by RadoslawKubas** [comment]
I will check everything with latest version asap.

**Comment by RadoslawKubas** [comment]
@jamesmontemagno I've created new pull request, this time compatible with Google Play Billing Library 4.0.0. Checked this new implementation in my own app and it seems to works perfectly.

**Pull request closed without merging**
