### PR TITLE
Add in app billing 4 for android

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Please take a moment to fill out the following:

Fixes # .

Changes Proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by philtomblin** [comment]
I've not had as much time this weekend as I had planned so haven't completed integrating this into my app yet. Only feedback so far is that you can remove IInAppBillingVerifyPurchase.shared.cs, since it should have been removed from everywhere else. I'll let you know when I've finished the refactoring...

**Comment by philtomblin** [comment]
@jamesmontemagno I can confirm this now works perfectly for iOS. I need to implement Android verification in my backend before I can check the app logic there.

**Comment by CartBlanche** [comment]
I'm assuming everyone received the Google emails this week about upgrading to v 4. Any rough idea when this PR is likely to be merged?

**Comment by philtomblin** [comment]
It's obviously in James' hands but, FWIW, I'm working on my Android app at the moment so am hoping to complete my own testing in the next week or so. This seems pretty solid so worth trying out nuget v5.0.1 beta, which corresponds to this, as far as I know.

**Comment by CartBlanche** [comment]
@philtomblin I miss wrote, I meant merged into `main` and therefore made stable. I am already using `v5.0.1 beta` but need to double check that it is using v4 under the hood.

**Comment by jamesmontemagno** [comment]
@CartBlanche so the email is that you need v3 or v4. We have used v3 for since v4.0 of the nuget

**Comment by jamesmontemagno** [comment]
v5.0 used v4 of billing :) i like how the numbers don't align at all.

So if you are using v4.0 of the nuget you are fine

**Comment by philtomblin** [comment]
@jamesmontemagno For completeness, I can confirm I have this working perfectly for Android subscriptions too. Thanks again for getting this sorted out so promptly!

**Pull request merged**
