### PR TITLE
start implementing v5

### LINKED ISSUE #521: When will you support version of Xamarin.Android.Google.BillingClient 5.1.0 ?
When will you support version of Xamarin.Android.Google.BillingClient 5.1.0 ?

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Fixes #521

### CODE REVIEW

**Comment by pulmuone** [comment]
version :
Plugin.InAppBilling 7.0.0-beta
Xamarin.Android.Google.BillingClient 6.0.0
Xamarin.AndroidX.Core 1.10.1.1
Xamarin.Forms 5.0.0.2578
VS 2022
Android 13

Error Source :
var purchase = await billing.PurchaseAsync(productIdSub, ItemType.Subscription);

Error Message :
Issue connecting: Java.Lang.NullPointerException: offerToken is required for constructing ProductDetailsParams.
at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/JniEnvironment.g.cs:11524
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00036] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:867
at Android.BillingClient.Api.BillingFlowParams+ProductDetailsParams+Builder.Build () [0x00000] in C:\a_work\1\s\generated\com.android.billingclient.billing\obj\Release\monoandroid12.0\generated\src\Android.BillingClient.Api.BillingFlowParams.cs:344
at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync (System.String productSku, System.String itemType, System.String obfuscatedAccountId, System.String obfuscatedProfileId) [0x00119] in D:\a\1\s\src\Plugin.InAppBilling\InAppBilling.android.cs:360
at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.InAppBilling.ItemType itemType, System.String obfuscatedAccountId, System.String obfuscatedProfileId) [0x00131] in D:\a\1\s\src\Plugin.InAppBilling\InAppBilling.android.cs:339
at BarcodeScanner.ViewModels.PaymentViewModel.PurchaseSubscription () [0x00314] in D:\01.SourcePrivate\BarcodeScanner2\BarcodeScanner\BarcodeScanner\ViewModels\PaymentViewModel.cs:273
--- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: offerToken is required for constructing ProductDetailsParams.
at com.google.android.gms.internal.play_billing.zzm.zzc(com.android.billingclient:billing@@6.0.0:1)
at com.android.billingclient.api.BillingFlowParams$ProductDetailsParams$Builder.build(com.android.billingclient:billing@@6.0.0:2)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by jamesmontemagno** [comment]
Thanks for testing it out. I think they changed this in v6 compared to v5.

Test out 7.0.1-beta for me as I now set it.

**Comment by pulmuone** [comment]
7.0.1-beta  ok good.
great job, thank you.

**Comment by pulmuone** [comment]
7.0.1-beta  Bug add.

var items = await billing.GetProductInfoAsync(ItemType.Subscription,);
var item = items.FirstOrDefault(i => i.ProductId == productIdSub);

item.LocalizedPrice;  <- null

image

**Comment by jamesmontemagno** [comment]
Thanks for testing, just pushed 7.0.2

you will need to look into the AndroidExtras, which has the subs details

**Comment by pulmuone** [comment]
7.0.2-beta 
LocalizedPrice is null in version 7.0.2-beta. Is the LocalizedPrice field no longer supported?
image

**Comment by pulmuone** [comment]
Get subscription price from 7.0.2-beta In Android
The LocalizedPrice column will only be used on iOS.

image

**Comment by jamesmontemagno** [comment]
yes, that is correct, you could just write it like this....

```csharp
var p = item.AndroidExtras?.SubscriptionOfferDetails?.FirstOrDefault(s => s.BasePlanId == "p1m")?.PricingPhases?.FirstOrDefault()?.FormattedPrice ?? null;

if(p is not null)
	Settings.SubPrice = p;
```

Maybe I should do this for people...

**Comment by jamesmontemagno** [comment]
Alright, try 7.0.3 beta..

I now fill in the information on the main product item with the first subscription offer. This will be nicer and more backwards compatible for sure.

**Comment by ecosimini** [comment]
Thanks @jamesmontemagno et al.

Got NuGet v7.0.5 and had some warnings but all billing regression testing worked without needing any code changes (on MAUI 7.0 app). After releasing and uploading to Google Play I'm no longer getting that nasty old billing library warning :)

For ref the warnings I'm getting now are:
JAVAC : warning : unknown enum constant Scope.LIBRARY
JAVAC : warning : unknown enum constant Scope.LIBRARY_GROUP_PREFIX
JAVAC : warning : unknown enum constant Scope.LIBRARY_GROUP

I get those repeating like 50 times. Anyone also getting those after updating to 7.0.5 or know how to fix? I had a super clean build with no warnings before :(

**Comment by Nick1611** [comment]
Hi,

I am testing migration from version 5 to 7.0.5. I found issues with subscription items (monthly & yearly) with free trial for users who never had any subscription.

**Test case 1:** User who had subscription, free trial is not eligible. Product LocalizedPrice & MicrosPrice can be retrieved correctly. Product subscription works.

**Test case 2:** User who never had any subscription, free trial is available. 
The product.AndroidExtras…PricingPhase contains 2 records:

- BillingPeriod “P1W”, PriceAmountMicros “0”
- BillingPeriod “P1M” (or “P1Y” for yearly subscription), PriceAmountMicros “99”


**Issue 1:** In change “[Return info of first sub into default info for simplicity](https://github.com/jamesmontemagno/InAppBillingPlugin/pull/532/commits/252979f064c134cbd68fe471a66696b375de7c3f)”, 
“var firstSub = subs?.FirstOrDefault()?.PricingPhases?.FirstOrDefault()” returns the first pricing phase would get the free trial phase of 0. 
It should return the first pricing phase where PriceAmountMicros != 0.

**Issue 2:** When execute “CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.Subscription)”, Google prompt error on device “This version of the application is not configured for billing through Google Play. Check the help center for more information”. 

It ended up with InAppBillingPurchaseException:
- PurchaseError: “Plugin.InAppBilling.PurchaseError.DeveloperError”, 
- message: "Unable to process purchase."  

It seems that more information is required to be passed into Google Play for subscription with eligible free trial.


Thanks,

Nick

**Pull request merged**
